---
executors:
  golang:
    docker:
    - image: cimg/go:1.17

version: 2.1
jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run: go mod download
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
      - run: golangci-lint run
      - run: make
      - run: cd /tmp && curl -L --remote-name https://github.com/goreleaser/goreleaser/releases/download/v1.8.3/goreleaser_Linux_x86_64.tar.gz
      - run: cd /tmp && curl -L --remote-name https://github.com/goreleaser/goreleaser/releases/download/v1.8.3/checksums.txt
      - run: cd /tmp && sha256sum --ignore-missing -c checksums.txt
      - run: mkdir -p /home/circleci/.local/bin
      - run: tar -C /home/circleci/.local/bin -xf /tmp/goreleaser_Linux_x86_64.tar.gz goreleaser
      - run: goreleaser release --skip-publish --snapshot --debug
      - store_artifacts:
          path: dist

  release:
    executor: golang

    steps:
    - checkout
    - run: go mod download
    - run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | BINDIR=/home/circleci/.local/bin sh
    - run: goreleaser release

workflows:
  version: 2
  stuff:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
